services:
  rag-app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rag_db
      - DB_USER=macdedylan
      - DB_PASSWORD=password
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: macdedylan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: